const config = {
  cells: [
    { title: "My Website", url: "https://napsternpt.github.io/", icon: "https://napsternpt.github.io/assets/logo.png", cols: 2, rows: 2 },
    { title: "My GitHub", url: "https://github.com/NapsterNPT?tab=repositories", icon: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg", cols: 1, rows: 2 },
    { title: "Title", url: "Link", icon: "Logo", cols: 2, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 2 },
    { title: "Title", url: "Link", icon: "Logo", cols: 2, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 2, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 2 },
    { title: "Title", url: "Link", icon: "Logo", cols: 2, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 2, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 2, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 2 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
    { title: "Title", url: "Link", icon: "Logo", cols: 1, rows: 1 },
  ]
};
